### ISSUE TITLE
2.3.2 桌面端和移动端的差异 P43

### ISSUE THREAD

**Issue by smartisantt** [zhangxinxu/htmlapi#2]
` 在桌面端，页面的默认的滚动条是<html>元素产生的，而在移动端，该滚动条是<body>元素产生的`
这个跟实测不符。

**Comment by zhangxinxu** [comment]
如何测试的？

**Comment by smartisantt** [comment]
1. 手机和电脑访问同样代码的页面，`<button onclick="alert(document.scrollingElement.tagName)">click</button>` 点击按钮后都输出 `HTML`
2. 设置html overflow:hidden 手机和电脑访问同样代码的页面窗体都没有产生滚动条
测试手机安卓手机，chrome浏览器

**Comment by zhangxinxu** [comment]
感谢反馈，确实是，现在移动端手机已经磨平此差异了。
